databases:
  - name: study-db
    plan: free
    databaseName: studyaidb
    user: studyai_user

services:
  - type: web
    name: ai-study-planner
    env: python
    plan: free

    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --threads 2 --timeout 60 --max-requests 500 --max-requests-jitter 50

    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7

      - key: SECRET_KEY
        generateValue: true

      - key: FLASK_DEBUG
        value: "false"

      - key: DATABASE_URL
        fromDatabase:
          name: study-db
          property: connectionString

      - key: CLOUDINARY_CLOUD_NAME
        sync: false

      - key: CLOUDINARY_API_KEY
        sync: false

      - key: CLOUDINARY_API_SECRET
        sync: false

      - key: MAIL_SERVER
        value: smtp.gmail.com

      - key: MAIL_PORT
        value: "587"

      - key: MAIL_USE_TLS
        value: "true"

      - key: MAIL_USERNAME
        sync: false

      - key: MAIL_PASSWORD
        sync: false

      - key: MAIL_DEFAULT_SENDER_NAME
        value: "StudyAI Academic Support"

      - key: FIREBASE_API_KEY
        value: "AIzaSyDgVHh-UvQcT-qFJeNYORYx8QlWOijDmSI"

      - key: FIREBASE_AUTH_DOMAIN
        value: "studyai-f8351.firebaseapp.com"

      - key: FIREBASE_PROJECT_ID
        value: "studyai-f8351"

      - key: FIREBASE_STORAGE_BUCKET
        value: "studyai-f8351.firebasestorage.app"

      - key: FIREBASE_MESSAGING_SENDER_ID
        value: "44359729730"

      - key: FIREBASE_APP_ID
        value: "1:44359729730:web:43ab31f39d9eaa6d51e3db"

      - key: FIREBASE_MEASUREMENT_ID
        value: "G-2V6TXE54Q0"
